version: '3'

tasks:
  setup:
    silent: true
    cmds:
      - cargo install cargo-nextest

  build:
    silent: true
    cmds:
      - task: build:default

  build:default:
    silent: true
    cmds:
      - cargo build

  build:release:
    silent: true
    cmds:
      - cargo build --release

  test:
    silent: true
    cmds:
      - task: test:default

  test:default:
    silent: true
    cmds:
      - docker-compose up -d
      - cargo nextest run

  lint:
    silent: true
    cmds:
      - task: lint:default

  lint:default:
    silent: true
    cmds:
      - cargo fmt --all -- --check
      - cargo clippy -- -D warnings

  lint:fix:
    silent: true
    cmds:
      - cargo fmt --all
      - cargo clippy

  run:
    silent: true
    cmds:
      - task: run:api

  run:api:
    silent: true
    cmds:
      - docker-compose up -d
      - cargo run -p bipa-api

  run:worker:
    silent: true
    cmds:
      - docker-compose up -d
      - cargo run -p bipa-worker

  docker:up:
    silent: true
    cmds:
      - docker-compose up

  docker:down:
    silent: true
    cmds:
      - docker-compose down

  docker:destroy:
    silent: true
    cmds:
      - docker-compose down -v

  k8s:build:
    silent: true
    cmds:
      - docker build --target api -t bipa-api:latest .
      - docker build --target worker -t bipa-worker:latest .

  k8s:up-infra:
    silent: true
    cmds:
      - cat local/k8s/infra.yaml | sed "s|\$ROOT_DIR|$PWD|g" | kubectl apply -f -

  k8s:up-app:
    silent: true
    cmds:
      - cat local/k8s/app.yaml | sed "s|\$ROOT_DIR|$PWD|g" | kubectl apply -f -

  k8s:up:
    silent: true
    cmds:
      - task: k8s:up-infra
      - task: k8s:up-app

  k8s:down-infra:
    silent: true
    cmds:
      - cat local/k8s/infra.yaml | sed "s|\$ROOT_DIR|$PWD|g" | kubectl delete -f -

  k8s:down-app:
    silent: true
    cmds:
      - cat local/k8s/app.yaml | sed "s|\$ROOT_DIR|$PWD|g" | kubectl delete -f -

  k8s:down:
    silent: true
    cmds:
      - task: k8s:down-infra
      - task: k8s:down-app

  clean:
    silent: true
    cmds:
      - sh rust_cleaner.sh
